### ISSUE TITLE
Support for marketplace plugins in a custom RunIdeTask in 2.0

### ISSUE THREAD

**Issue by abrooksv** [JetBrains/gradle-intellij-plugin#1553] opened 2024-03-05 22:53 UTC
### Describe the need of your request

Since there is no RubyMine support, we need to use IntelliJ Ultimate with the Ruby plugin from the marketplace. Today you cannot make a custom task and add additional plugins to it, only the bundled plugins are present.

It would be nice to be able to include plugins from the marketplace as well as disable plugins if need be to test different plugin permutations.

### Proposed solution

```
        register<RunIdeTask>("runIntelliJUltimate") {
            type = IntelliJPlatformType.IntellijIdeaUltimate
            version = providers.gradleProperty("platformVersion")
            marketplacePlugins("org.jetbrains.plugins.ruby:.....")
            disabledPlugins("Git4Idea")
        }
```

### Alternatives you've considered

Allow for completely custom configurations to be defined with an `intellijPlatform {}` and then use something like `configuration = myCustomConfig`, but that is probably harder to manage and explain then the above automating the PrepareSandbox tasks and creating a per sandbox `INTELLIJ_PLATFORM_PLUGINS_EXTRACTED`

**Comment by YannCebron** [comment] 2024-03-06 09:33
Duplicates #1431 ?

**Comment by abrooksv** [comment] 2024-03-06 14:59
It isn't supported today in the 2.0 branch, @hsz asked me to cut an issue to track it

**Comment by YannCebron** [comment] 2024-03-06 15:17
Sorry wrong link. AFAIU it is a duplicate of https://github.com/JetBrains/gradle-intellij-plugin/issues/1489 which is targeted for 2.x

**Closed** 2024-03-06 15:45 UTC
Labels: enhancement
