### ISSUE TITLE
Compile with rsocket-rpc fails

### ISSUE THREAD

**Issue by DominikWojciechowski** [JetBrains/gradle-intellij-plugin#456] opened 2020-01-21 11:42 UTC
## Expected Behavior
A project with both gradle-intellij-plugin and rsocket-rpc compile successfully. 
## Current Behavior

When both gradle-intellij-plugin and rsocket-rpc are configured in Gradle build file, build process fails on compileJava with the following message (for readability on Pastebin, and attached below [out-error.log](https://github.com/JetBrains/gradle-intellij-plugin/files/4090883/out-error.log) [out.log](https://github.com/JetBrains/gradle-intellij-plugin/files/4090884/out.log)) : [Pastebin](https://pastebin.com/DY4NWWLg)

## Steps to Reproduce
1. Pull example repository [github](https://github.com/DominikWojciechowski/exampleProjectForIssue)
2. install protoc on your machine (please follow this link [protobuf](https://github.com/protocolbuffers/protobuf) or use a handy tool like [chocolatey](https://chocolatey.org/)
3. Import project to IntelliJ IDEA 
4. Execute Gradle tasks "clean" and "build"
5. Observe error message on the console 😉 
6. Copy contents from "buildWithoutIntellijPlugin.gradle.kts" to "build.gradle.kts"
7. Execute Gradle tasks "clean" and "build"
8. Build should pass this time.

## Context (Environment)

I am implementing [opensource plugin](https://gitlab.com/wojciechowskid/wncplugin) to IntelliJ idea which will connect to another program on another machine via rsocket-rpc. I need to have generated and compiled java files o be able to use RPC goodness. 

## Detailed Description

I have no experience in Gradle plugin development and I am not able to find out where exactly problem is. Maybe in the debug session, there would be a possibility to find exact solution

**Comment by zolotov** [comment] 2020-01-22 04:17
Hi,

Thank you for the detailed report.

Apparently, generated code depends on the protobuf library different from the one that IntelliJ includes. Might be related to #239. 

Could you try to replace `implementation` protobuf-java dependency with the `compile` one?

**Comment by DominikWojciechowski** [comment] 2020-01-22 07:07
> Could you try to replace `implementation` protobuf-java dependency with the `compile` one?

Quick check result: compilation successful. I'll check if the plugin works as expected, later this day.

**Comment by DominikWojciechowski** [comment] 2020-01-22 10:55
> Quick check result: compilation successful. I'll check if the plugin works as expected, later this day.

Ok, It works. Thank you for this workaround! 
But I think it is not a solution, because it would stop working in Gradle 7.0.

**Comment by zolotov** [comment] 2020-01-23 08:45
thanks for the update. closing as duplicate of #239

**Closed by zolotov** 2020-01-23 08:45 UTC
Labels: feedback required

**Comment by zolotov** [comment] 2021-04-23 14:31
it seems it's not a #239 but #454. please try the workaround described here: https://github.com/JetBrains/gradle-intellij-plugin/issues/454#issuecomment-825696334. Does it help?
