### ISSUE TITLE
Gradle fails to resolve multi-module plugin project when using gradle-intellij-plugin 1.10.0

### ISSUE THREAD

**Issue by Gasloff** [JetBrains/gradle-intellij-plugin#1223] opened 2022-11-25 10:22 UTC
**Description of the bug**
When using gradle-intellij-plugin version 1.10.0 Gradle fails to load tasks for multi-module plugin project.

We have rather complex project structure, that contains several modules and "bootstrap" module that combines them together. After changing idea version to 223.7571.58-EAP-SNAPSHOT and gradle-intellij-plugin version to 1.10.0 there are  warnings on Gradle build for each module: `Can not load tasks for project`.
And no intellij-platform dependencies available.

**To Reproduce**
I've prepeared simple demo plugin project with similar structure, where the issue can be reproduced:
[https://github.com/Gasloff/demo-idea-plugin](https://github.com/Gasloff/demo-idea-plugin)
Clone and open the project.
Run Gradle refresh. It says BUILD SUCCESSFUL but we have warnings for each module and the following stacktrace in console:
```
Can not load tasks for project ':demo-bootstrap'

org.gradle.api.internal.tasks.DefaultTaskContainer$TaskCreationException: Could not create task ':demo-bootstrap:setupDependencies'.
	at org.gradle.api.internal.tasks.DefaultTaskContainer.taskCreationException(DefaultTaskContainer.java:715)
	at org.gradle.api.internal.tasks.DefaultTaskContainer.access$600(DefaultTaskContainer.java:76)
	at org.gradle.api.internal.tasks.DefaultTaskContainer$TaskCreatingProvider.domainObjectCreationException(DefaultTaskContainer.java:707)
	at org.gradle.api.internal.DefaultNamedDomainObjectCollection$AbstractDomainObjectCreatingProvider.tryCreate(DefaultNamedDomainObjectCollection.java:948)
	at org.gradle.api.internal.tasks.DefaultTaskContainer$TaskCreatingProvider.access$1401(DefaultTaskContainer.java:654)
	at org.gradle.api.internal.tasks.DefaultTaskContainer$TaskCreatingProvider$1.run(DefaultTaskContainer.java:680)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
	at org.gradle.api.internal.tasks.DefaultTaskContainer$TaskCreatingProvider.tryCreate(DefaultTaskContainer.java:676)
	at org.gradle.api.internal.DefaultNamedDomainObjectCollection$AbstractDomainObjectCreatingProvider.calculateOwnValue(DefaultNamedDomainObjectCollection.java:929)
	at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:102)
	at org.gradle.api.internal.provider.Collectors$ElementFromProvider.collectEntries(Collectors.java:100)
	at org.gradle.api.internal.provider.Collectors$TypedCollector.collectEntries(Collectors.java:333)
	at org.gradle.api.internal.provider.Collectors$TypedCollector.collectInto(Collectors.java:328)
	at org.gradle.api.internal.collections.DefaultPendingSource.realize(DefaultPendingSource.java:61)
	at org.gradle.api.internal.collections.DefaultPendingSource.realizePending(DefaultPendingSource.java:39)
	at org.gradle.api.internal.collections.SortedSetElementSource.iterator(SortedSetElementSource.java:63)
	at org.gradle.api.internal.DefaultDomainObjectCollection.iterator(DefaultDomainObjectCollection.java:128)
	at org.gradle.api.internal.tasks.DefaultTaskContainer.iterator(DefaultTaskContainer.java:620)
	at java.base/java.util.AbstractCollection.addAll(AbstractCollection.java:351)
	at java.base/java.util.TreeSet.addAll(TreeSet.java:312)
	at java.base/java.util.TreeSet.<init>(TreeSet.java:160)
	at org.jetbrains.plugins.gradle.tooling.builder.TasksFactory.getAllTasks(TasksFactory.java:56)
	at org.jetbrains.plugins.gradle.tooling.builder.TasksFactory.collectTasks(TasksFactory.java:46)
	at org.jetbrains.plugins.gradle.tooling.builder.TasksFactory.getTasks(TasksFactory.java:78)
	at org.jetbrains.plugins.gradle.tooling.builder.ExternalProjectBuilderImpl.getTasks(ExternalProjectBuilderImpl.groovy:171)
	at org.jetbrains.plugins.gradle.tooling.builder.ExternalProjectBuilderImpl.doBuild(ExternalProjectBuilderImpl.groovy:108)
	at org.jetbrains.plugins.gradle.tooling.builder.ExternalProjectBuilderImpl.buildAll(ExternalProjectBuilderImpl.groovy:75)
	at org.jetbrains.plugins.gradle.tooling.internal.ExtraModelBuilder.buildAll(ExtraModelBuilder.java:107)
	at org.jetbrains.plugins.gradle.tooling.internal.ExtraModelBuilder.buildAll(ExtraModelBuilder.java:76)
	at org.gradle.tooling.provider.model.internal.DefaultToolingModelBuilderRegistry$BuilderWithParameter.build(DefaultToolingModelBuilderRegistry.java:287)
	at org.gradle.tooling.provider.model.internal.DefaultToolingModelBuilderRegistry$UserCodeAssigningBuilder.lambda$build$0(DefaultToolingModelBuilderRegistry.java:374)
	at org.gradle.configuration.internal.DefaultUserCodeApplicationContext$CurrentApplication.reapply(DefaultUserCodeApplicationContext.java:109)
    ...
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.gradle.api.InvalidUserDataException: Cannot change dependencies of dependency configuration ':demo-bootstrap:compileOnly' after it has been included in dependency resolution.
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.preventIllegalMutation(DefaultConfiguration.java:1384)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.validateMutation(DefaultConfiguration.java:1344)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.extendsFrom(DefaultConfiguration.java:395)
	at org.jetbrains.intellij.IntelliJPlugin$configureSetupDependenciesTask$1$ideaConfiguration$1$1.invoke(IntelliJPlugin.kt:1494)
	at org.jetbrains.intellij.IntelliJPlugin$configureSetupDependenciesTask$1.invoke(IntelliJPlugin.kt:1496)
	at org.jetbrains.intellij.IntelliJPlugin$configureSetupDependenciesTask$1.invoke(IntelliJPlugin.kt:114)
	at org.jetbrains.intellij.IntelliJPlugin$inlined$sam$i$org_gradle_api_Action$0.execute(TaskContainerExtensions.kt)
	at org.gradle.api.internal.DefaultMutationGuard$2.execute(DefaultMutationGuard.java:44)
	...

```
No intellij dependencies available:
<img width="917" alt="Screenshot 2022-11-25 at 14 12 30" src="https://user-images.githubusercontent.com/8830197/203958807-1e4e6449-f0d5-4ee7-9cf0-b4d9b5e9e654.png">

**Expected behavior**
Checkout `idea_222` branch with idea 222.* and plugin 1.9.0. Gradle successfuly imports the project, all dependencies available. You can execute `runIde` task to see that DemoStartupActivity class works as expected.

**Environment:**
 - OS: macOS
 - Gradle IntelliJ Plugin Version 1.10.0
 - Gradle Version 7.5.1

**Additional context**
When switched to version 1.10.0-SNAPSHOT first time several days ago, the issue did not reproduce.
Seems to be related to [https://github.com/JetBrains/gradle-intellij-plugin/issues/1196](https://github.com/JetBrains/gradle-intellij-plugin/issues/1196)

**Comment by bric3** [comment] 2022-11-28 09:49
The stack trace is similar to the one in my comment in #1209

**Comment by hsz** [comment] 2022-12-01 07:41
This is indeed a duplicate of #1209. Please track that issue for more details – the fix is already available for testing.

**Closed by hsz** 2022-12-01 07:41 UTC
Labels: bug, duplicate, regression
