### ISSUE TITLE
'compilerClassPathFromMaven' doesn't have a configured value.

### ISSUE THREAD

**Issue by DemonWitch** [JetBrains/gradle-intellij-plugin#1003] opened 2022-05-30 14:11 UTC
when i use 1.6.0 , and  exexcute "runIde", i got this error 

A problem was found with the configuration of task ':instrumentCode' (type 'IntelliJInstrumentCodeTask').
  - In plugin 'org.jetbrains.intellij' type 'org.jetbrains.intellij.tasks.IntelliJInstrumentCodeTask' property 'compilerClassPathFromMaven' doesn't have a configured value.

macos 
arm64

**Comment by YannCebron** [comment] 2022-05-30 14:18
please link your project, or provide at minimum your target platform type/version used

**Comment by DemonWitch** [comment] 2022-05-31 06:30
here is my 'build.gradle.kts':
plugins {
    id("org.jetbrains.intellij") version "1.6.0"
    java
}
intellij {
    version.set("2022.1.1")
}
----
and my idea version is also 2022.1.1
my os is macos 12.3.1  arm64

**Comment by ekudel** [comment] 2022-06-02 11:10
I have the same issue. It seems to happen time to time. 

- IntelliJ version: 213-EAP-SNAPSHOT
- IntelliJ-Gradle plugin's version: 1.6.0
- Gradle: 7.4.2
- Internet works

I also get the following messages before the failure:

```
[gradle-intellij-plugin :common-rest-client:common-rest-client:instrumentCode] Cannot resolve java-compiler-ant-tasks in version: 213-EAP-SNAPSHOT
[gradle-intellij-plugin :common-rest-client:common-rest-client:instrumentCode] Cannot resolve java-compiler-ant-tasks in version: 213
Download https://cache-redirector.jetbrains.com/www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/java/java-gui-forms-rt/212.5712.53/java-gui-forms-rt-212.5712.53.jar, took 365 ms (30.58 kB)
Download https://cache-redirector.jetbrains.com/www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/java/java-compiler-instrumentation-util/212.5712.53/java-compiler-instrumentation-util-212.5712.53.jar, took 392 ms (55.49 kB)
Download https://cache-redirector.jetbrains.com/www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/java/java-gui-forms-compiler/212.5712.53/java-gui-forms-compiler-212.5712.53.jar, took 532 ms (137.45 kB)
[gradle-intellij-plugin :common-rest-client:common-rest-client:instrumentCode] Cannot resolve java-compiler-ant-tasks in version: 212.5712.53
```

**Comment by hsz** [comment] 2022-06-06 06:22
Thanks for the details, @ekudel.
For `213-EAP-SNAPSHOT`, Gradle resolves:
- https://cache-redirector.jetbrains.com/www.jetbrains.com/intellij-repository/snapshots/com/jetbrains/intellij/java/java-gui-forms-rt/213-EAP-SNAPSHOT/java-gui-forms-rt-213-EAP-SNAPSHOT.jar
- https://cache-redirector.jetbrains.com/www.jetbrains.com/intellij-repository/snapshots/com/jetbrains/intellij/java/java-compiler-instrumentation-util/213-EAP-SNAPSHOT/java-compiler-instrumentation-util-213-EAP-SNAPSHOT.jar
- https://cache-redirector.jetbrains.com/www.jetbrains.com/intellij-repository/snapshots/com/jetbrains/intellij/java/java-gui-forms-compiler/213-EAP-SNAPSHOT/java-gui-forms-compiler-213-EAP-SNAPSHOT.jar
- https://cache-redirector.jetbrains.com/www.jetbrains.com/intellij-repository/snapshots/com/jetbrains/intellij/java/java-compiler-ant-tasks/213-EAP-SNAPSHOT/java-compiler-ant-tasks-213-EAP-SNAPSHOT.jar
- https://cache-redirector.jetbrains.com/www.jetbrains.com/intellij-repository/snapshots/com/jetbrains/intellij/java/java-compiler-instrumentation-util-java8/213-EAP-SNAPSHOT/java-compiler-instrumentation-util-java8-213-EAP-SNAPSHOT.jar

And all the files are available.
I'm wondering if `--refresh-dependencies` would help in case of such an issue.

**Comment by DemonWitch** [comment] 2022-06-06 10:35
```
> Task :instrumentCode
[gradle-intellij-plugin :koca-plugin:instrumentCode] Cannot resolve java-compiler-ant-tasks in version: 212.5080.55
[gradle-intellij-plugin :koca-plugin:instrumentCode] Cannot resolve java-compiler-ant-tasks in version: 212.5080.55

> Task :instrumentCode FAILED
6 actionable tasks: 3 executed, 3 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':instrumentCode' (type 'IntelliJInstrumentCodeTask').
  - In plugin 'org.jetbrains.intellij' type 'org.jetbrains.intellij.tasks.IntelliJInstrumentCodeTask' property 'compilerClassPathFromMaven' doesn't have a configured value.
    
    Reason: This property isn't marked as optional and no value has been configured.
    
    Possible solutions:
      1. Assign a value to 'compilerClassPathFromMaven'.
      2. Mark property 'compilerClassPathFromMaven' as optional.
```
My Internet works fine, and any other version(1.5.3 1.4.0 and so on) can run successfully

I've also switched to mobile internet but I still got this error.
Maybe @ekudel. is right, the reason is probably that the JetBrains' resource is not accessible in some situations
Or maybe not? I have no idea.

**Comment by ekudel** [comment] 2022-06-10 16:13
I tried to run "gradlew --refresh-dependencies" and it didn't help

**Comment by ekudel** [comment] 2022-06-13 15:22
Actually it probably was just a coincidence. It may not be connected with the resources availability. I've just faced the following:
1. Got the error
2. Enabled VPN
3. Got the same error
4. Disabled VPN
5. The error disappears

**Comment by hsz** [comment] 2022-06-21 10:50
Thank you for providing more details on that! I'll close this issue as not reproducible, networking issue.

**Comment by ekudel** [comment] 2022-06-21 11:22
Actually my last comment pointed that this is probably not networking issue, because it started working after I just enable and then disable VPN. Also please note that this issue appeared about 1-2 months ago (I'm not sure about the exact moment) and never appeared previously.

**Comment by SingingBush** [comment] 2022-06-22 23:03
this is definitely not a network problem. I've just encountered it locally when doing some work to update a plugin to use Intellij 2022.1 as target version and Kotlin api version to 1.6 (because Intellij 2022.1 is bundled with bundled Kotlin 1.6.20):

```
> Task :instrumentTestCode FAILED
:instrumentTestCode (Thread[Execution worker for ':',5,main]) completed. Took 2.889 secs.

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':instrumentTestCode' (type 'IntelliJInstrumentCodeTask').
  - In plugin 'org.jetbrains.intellij' type 'org.jetbrains.intellij.tasks.IntelliJInstrumentCodeTask' property 'compilerClassPathFromMaven' doesn't have a configured value.
    
    Reason: This property isn't marked as optional and no value has been configured.
    
    Possible solutions:
      1. Assign a value to 'compilerClassPathFromMaven'.
      2. Mark property 'compilerClassPathFromMaven' as optional.
    
    Please refer to https://docs.gradle.org/7.4.2/userguide/validation_problems.html#value_not_set for more details about this problem.
```

I'm using gradle-intellij-plugin 1.5.3 as 1.6.0 won't work due to #998

**Comment by SingingBush** [comment] 2022-06-22 23:16
Seems that this problem may have been due to a previous error in which the Java process had not finished. After killing all my java processes and re-running I was able to successfully build without this problem.

**Comment by hsz** [comment] 2022-06-25 17:48
After a pretty exhaustive investigation, I have spotted two very different reasons that end up with such an error:

1. When running Gradle using Java 11.0.2, there's an issue with fetching resources via HTTPS – described in [JDK-8220723](https://bugs.openjdk.org/browse/JDK-8220723) issue. To fix that, update your environment t use the latest available patch of your JDK.
2. For isolated environments, like in the case of a corporate network that relies on an internal Maven repo that mirrors all necessary dependencies, the plugin-related repositories were pushed to the top of the list that Gradle used for resolving dependencies. Now I have changed to keep the project-level custom repository on the top, then use plugin-level repositories and common public repositories, like Maven Central, Google, etc.

@SingingBush, is it possible to reproduce your case (in case it wasn't caused by any of the above issues)? A full stack trace, and running task with at least `--info` would be helpful here.

Folks, please run your tasks with the `--refresh-dependencies` flag to ensure it re-fetches the latest available `1.7.0-SNAPSHOT` as it may become stale due to the unchanged version number.

**Comment by SingingBush** [comment] 2022-06-25 21:21
I've pushed a branch with the plugin updated to `1.7.0-SNAPSHOT` it results in a test that fails due to a `java.lang.NoClassDefFoundError` yet the change https://github.com/intellij-dlanguage/intellij-dlanguage/commit/d6b6110a4e4a257c51b2a6f98f480b46d8ad70f8 is only the update to plugin version. 

JDK's used are:
11.0.15 for the 2022.1.* builds
17.0.3 for the EAP_SNAPSHOT build

of course being Github Action there is no mirror for maven

https://github.com/intellij-dlanguage/intellij-dlanguage/actions/runs/2561940012

**Comment by SingingBush** [comment] 2022-06-25 22:16
I've pushed a commit that adds `--debug` to the gradle build. See builds here: https://github.com/intellij-dlanguage/intellij-dlanguage/actions/runs/2562056971

**Closed** 2022-07-06 11:40 UTC
Labels: bug

**Comment by ralphhuang** [comment] 2022-09-09 02:47
jdk11.0.2    has this error
jdk11.0.16  error disappeared

**Comment by adietish** [comment] 2022-10-24 12:53
> jdk11.0.2 has this error jdk11.0.16 error disappeared
> 
> -----other env 'org.jetbrains.intellij' version '1.9.0' MAC OSX gradle 7.5.1

I can confirm the solution. With java.net 11.0.2 I ran into this error while I didn't when I used liberica jdk 11.0.7.
