### ISSUE TITLE
Self update check should be off by default

### ISSUE THREAD

**Issue by blundell** [JetBrains/gradle-intellij-plugin#1282] opened 2023-01-18 13:09 UTC
**Describe the bug**
As mentioned here: https://github.com/gradle/gradle/issues/23564 it seems that this plugin is being ran in an environment where gradle.properties cannot be set. Therefore if the self update check was set to false by default, then nothing would run from this plugin when it shouldn't.

Setting default code is here: https://github.com/JetBrains/gradle-intellij-plugin/blob/master/src/main/kotlin/org/jetbrains/intellij/BuildFeature.kt#L11

side note:
If I am using "the latest version" and run the build, then a new version comes out, my next build will fail because I'm not on the latest version? isn't this another reason to have the default as false.

**Expected behavior**

The build should be reproducible and pass each time.

**Environment:**
 - macOS
 - Gradle IntelliJ Plugin Version 1.10.2
 - Gradle Version 7.6

**Comment by hsz** [comment] 2023-01-18 13:43
Thanks for reporting, Paul.

This flag cannot be set to `false` by default, as its purpose is to educate plugin users about new version availability. The actual issue is that developers bump the IDE version they want to use, ensuring the plugin is also fresh.

Extracting this check as a separate task that will run first could help. WDYT?

**Comment by blundell** [comment] 2023-01-18 13:53
Thanks! I don't have the best Gradle foo, but that sounds logical to me. 
At the moment there is no way to configure plugins through flags/props when ran in the above 'synthetic root' project way. But if it was a separate task, perhaps the task can always be configurable? I am not sure myself tbh.

**Comment by hfhbd** [comment] 2023-01-18 20:07
With dependabot and/or renovatebot I don't see a use case and I disabled the (annoying) check in my repos immediately.

**Comment by hsz** [comment] 2023-01-18 21:59
@blundell Could you please try the `1.12.1-SNAPSHOT` [snapshot release](https://plugins.jetbrains.com/docs/intellij/tools-gradle-intellij-plugin.html#snapshot-release)?

@hfhbd If the update message annoys you, it just means you weren't using the latest version. :)

**Comment by blundell** [comment] 2023-01-19 08:58
```
* What went wrong:
Configuration cache state could not be cached: field `__classPathFiles__` of task `:plugin:generateExternalPluginSpecBuilders` of type `org.gradle.kotlin.dsl.provider.plugins.precompiled.tasks.GenerateExternalPluginSpecBuilders`: error writing value of type 'org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection'
> Could not resolve all files for configuration ':plugin:compileClasspath'.
   > Could not find org.jetbrains.intellij.plugins:gradle-intellij-plugin:1.12.1-SNAPSHOT.
     Searched in the following locations:
       - file:/Users/pblundell/.m2/repository/org/jetbrains/intellij/plugins/gradle-intellij-plugin/1.12.1-SNAPSHOT/maven-metadata.xml
       - file:/Users/pblundell/.m2/repository/org/jetbrains/intellij/plugins/gradle-intellij-plugin/1.12.1-SNAPSHOT/gradle-intellij-plugin-1.12.1-SNAPSHOT.pom
       - https://oss.sonatype.org/content/repositories/snapshots/org/jetbrains/intellij/plugins/gradle-intellij-plugin/1.12.1-SNAPSHOT/maven-metadata.xml
       - https://oss.sonatype.org/content/repositories/snapshots/org/jetbrains/intellij/plugins/gradle-intellij-plugin/1.12.1-SNAPSHOT/gradle-intellij-plugin-1.12.1-SNAPSHOT.pom
       - https://plugins.gradle.org/m2/org/jetbrains/intellij/plugins/gradle-intellij-plugin/1.12.1-SNAPSHOT/maven-metadata.xml
       - https://plugins.gradle.org/m2/org/jetbrains/intellij/plugins/gradle-intellij-plugin/1.12.1-SNAPSHOT/gradle-intellij-plugin-1.12.1-SNAPSHOT.pom
     Required by:
         project :plugin

```

**Comment by hsz** [comment] 2023-02-09 16:44
Closing as the issue is resolved — will be published with the upcoming release.

FTR, since `1.12.3-SNAPSHOT`, the plugin is available as `org.jetbrains.intellij.plugins:gradle-intellij-plugin:1.12.3-SNAPSHOT` (plugin marker is also published to make proper redirections).

**Closed by hsz** 2023-02-09 16:44 UTC
Labels: bug
