### ISSUE TITLE
ListProductsReleases empty for 2023.3

### ISSUE THREAD

**Issue by nico-loeber** [JetBrains/gradle-intellij-plugin#1505] opened 2023-12-09 13:42 UTC
### What happened?

After updating my plugin for the 2023 release the `runPluginVerifier` Task failes with `'ideVersions' and 'localPaths' properties should not be empty` probably caused by `listProductsReleases` resulting an empty file.
Executing the tasks results in no error, the `idea_product_releases.xml` file is downloaded and looks like it would include suitable releases.

I tried to declare the version as `2023.3` but this didn't help. Switching back to 232 release results in everything working fine again.

Please let me know if this is caused by a configuration mistake.
[build.gradle.kts](https://github.com/php-perfect/ddev-intellij-plugin/blob/main/build.gradle.kts)
[plugin.xml](https://github.com/php-perfect/ddev-intellij-plugin/blob/main/src/main/resources/META-INF/plugin.xml)

### Steps to reproduce

Switch the target version of your plugin to 2023.3 release, by setting `version` to `IU-233.11799.241` or `2023.3` and check the output of the `listProductsReleases` or `printProductsReleases` tasks.

Relevant configuration:
```kotlin
// See https://github.com/JetBrains/gradle-intellij-plugin/
intellij {
    type.set("IU")
    version.set("IU-233.11799.241") // https://www.jetbrains.com/de-de/idea/download/other.html
    plugins.add("com.intellij.database") // bundled
    plugins.add("org.jetbrains.plugins.terminal") // bundled
    plugins.add("com.jetbrains.plugins.webDeployment") // bundled
    plugins.add("org.jetbrains.plugins.remote-run") // bundled
    plugins.add("Docker") // bundled
    plugins.add("NodeJS") // bundled
    plugins.add("org.jetbrains.plugins.node-remote-interpreter") // bundled
    plugins.add("com.jetbrains.php:233.11799.241") // https://plugins.jetbrains.com/plugin/6610-php/versions
    plugins.add("org.jetbrains.plugins.phpstorm-remote-interpreter:233.11799.172") // https://plugins.jetbrains.com/plugin/7511-php-remote-interpreter/versions
    plugins.add("org.jetbrains.plugins.phpstorm-docker:233.11799.232") // https://plugins.jetbrains.com/plugin/8595-php-docker/versions
}

tasks {
    listProductsReleases {
        types.set(listOf("IC", "IU", "PS", "WS", "DB"))
        releaseChannels.set(listOf(ListProductsReleasesTask.Channel.RELEASE))
    }
}
```

### Gradle IntelliJ Plugin version

1.16.1

### Gradle version

8.2.1

### Operating System

Linux

### Link to build, i.e. failing GitHub Action job

https://github.com/php-perfect/ddev-intellij-plugin/actions/runs/7130828331/job/19418086345?pr=270

**Comment by reloxx13** [comment] 2023-12-19 09:35
@hsz any news or plans? ddev plugin update is blocked by this.

**Comment by fsuter** [comment] 2023-12-22 08:48
I'm upvoting this too, as I'm eagerly awaiting the update of the DDEV plugin to update PhpStorm itself.

**Comment by begner** [comment] 2023-12-22 11:01
JAU (just another Upvote)

**Comment by hctom** [comment] 2023-12-25 13:42
Upvote from me as well, because I'd really like to be able to use the DDEV plugin again

**Comment by splatterb0y** [comment] 2023-12-25 20:18
Please fix, I'm still stuck with the older PHPStorm version because I really need the DDEV plugin.

**Comment by cleverhoods** [comment] 2023-12-27 12:38
up

**Comment by aweb3r** [comment] 2023-12-27 14:23
Up

**Comment by nico-loeber** [comment] 2023-12-30 12:08
I could really need some support on this. The only way to bypass this issue in my plugin release workflow is to skip the plugin verifyer entirely which I would really like to avoid.

@YannCebron, maybe you can help on this?

**Comment by jonnyhocks** [comment] 2024-01-03 10:06
Adding another upvote here 👍

**Comment by RubenColpaert** [comment] 2024-01-04 09:51
Best wishes for the new year and another upvote :+1:

**Comment by mhstudioos** [comment] 2024-01-04 10:04
Up

**Comment by ArneVerleyenIO** [comment] 2024-01-05 11:18
Up

**Comment by hsz** [comment] 2024-01-12 14:52
I'm sorry for the long silence. The issue is fixed and will be released soon.

**Closed by hsz** 2024-01-12 14:52 UTC
Labels: bug
