### ISSUE TITLE
Avoid IDEA downloading while importing gradle project

### ISSUE THREAD

**Issue by zolotov** [JetBrains/gradle-intellij-plugin#36] opened 2015-12-03 19:53 UTC

**Comment by YannCebron** [comment] 2020-10-15 10:49
duplicate of #123?

**Comment by zolotov** [comment] 2020-10-15 11:08
Not exactly. I'm not even sure it's possible to implement. We cannot avoid downloading while importing as in this case you'll get a project with a lot of red code because of missing dependencies. Probably, the idea was to avoid modal downloading process while opening the project, I'm not sure whether it's still the case.

**Comment by YannCebron** [comment] 2021-04-21 15:57
gradle import is not modal anymore

**Comment by zolotov** [comment] 2021-04-21 16:31
thanks. I think it can be closed then

**Closed** 2021-04-21 16:31 UTC
