### ISSUE TITLE
runIde task redownloads JBR roughly once per day

### ISSUE THREAD

**Issue by fcurts** [JetBrains/gradle-intellij-plugin#568] opened 2020-11-17 09:51 UTC
I've been observing this for weeks:

```
> Task :runIde
Download https://cache-redirector.jetbrains.com/jetbrains.bintray.com/intellij-jbr/jbr-11_0_6-osx-x64-b520.66.tar.gz
```

I think it's always the same URL.
I haven't double-checked if the JBR is actually downloaded, but something is clearly off.
I'm not deleting any files or directories in the project or Gradle cache.
I'm not changing the IntelliJ version to build and run against.

```
plugins {
  id("org.jetbrains.intellij") version "0.6.3"
}
intellij { version = "2019.3.5" }
```

Gradle 6.7
openjdk 11.0.6 2020-01-14
macOS 10.15.7

**Comment by simonolander** [comment] 2021-02-06 15:13
I'm experiencing this as well, and I can confirm that it is the same URL most of the time. Any progress or workarounds so far?

**Comment by hsz** [comment] 2021-05-06 21:41
JBR archives are downloaded from `https://cache-redirector.jetbrains.com/intellij-jbr` into the Gradle cache directory:

    ~/.gradle/caches/modules-2/files-2.1/com.jetbrains/jbre

As described in https://docs.gradle.org/4.10-rc-1/release-notes.html#periodic-cache-cleanup:

> Files in shared caches used by the current Gradle version in GRADLE_USER_HOME/caches/ (e.g. jars-3 or modules-2) are checked periodically (at most every 24 hours) for when they were last accessed. Depending on whether the file can be recreated locally or would have to be downloaded from a remote repository again, it will be deleted after 7 or 30 days of not being accessed, respectively.

@zolotov  Maybe we should consider changing the cache directory?

**Comment by zolotov** [comment] 2021-05-07 06:45
@hsz why are you bringing this up? The issue states about downloading per day, not per week. Also, I don’t think it’s happening to me even though I use the very same cache directories.

>  Maybe we should consider changing the cache directory

Only if there is a really good reason for that. At the moment I don’t see any. Cleanup is a wonderful long-awaited feature, that perfectly fits IDEA sdks and JBR distributions.

**Comment by mingshun** [comment] 2021-05-07 23:26
This upsets me so much. The download speed in China mainland is extremely slow (just 1~2 Kb/s). I have to wait more than 1 hour every time I start `runIde` task. Any progress or workarounds?

**Comment by vlsi** [comment] 2021-05-18 07:04
@hsz , I guess the issue is that you put the file into Gradle's folder, and you do not use Gradle's API to access it.
That is why Gradle assumes the file is *not* accessed, so it removes it.

By the way, have you considered using Gradle's `configuration` API to retrieve JBR? (see https://github.com/JetBrains/gradle-intellij-plugin/issues/660)

**Comment by hsz** [comment] 2021-05-31 21:03
As @vlsi suggested, I've migrated to Ivy-based resources handling, so both downloading and accessing files goest through Gradle.
As for now, I didn't notice any side effects regarding re-downloading JBR.
I'm going to close this ticket, but feel free to reopen it if any issues are observed.

**Closed by hsz** 2021-05-31 21:03 UTC
