### ISSUE TITLE
Using runIde or runIdea task is extremely slow

### ISSUE THREAD

**Issue by halirutan** [JetBrains/gradle-intellij-plugin#210] opened 2017-06-30 13:02 UTC
Using the Gradle tasks to run the IDEA sandbox is extremely slow since Gradle is running all the time in the background. Closing the Gradle tool-window helps a bit but it still lacks noticeably.

The best solution for me was to use both Gradle and an IDEA plugin module that I use for debugging and testing. However, setting things up correctly is not obvious and currently I proceed as follows:

1. Import the project as Gradle project
2. Closing the project and importing it again as IDEA Plugin module
3. Fixing the .iml file manually to make it a `PLUGIN_MODULE` and setting up `"DevKit.ModuleBuildProperties"` so that I can create a run config. Why this is not done automatically, I'm not sure of.
4. Create a run config independent of Gradle (which is only possible if you did step 3. correctly)

I must be doing something wrong. Is there an easier way?

**Comment by zolotov** [comment] 2017-06-30 19:05
What exactly is slow? Gradle? Host IDE? IDE that you run via gradle?

There is no way to mix plugins and gradle module type and it's not supposed to do. You have to choose what model you want to use

**Comment by ben-gibson** [comment] 2017-10-30 19:00
I have a similar issue using the runIdea task, but the CPU load drops of if I close the run tool window.

**Comment by zolotov** [comment] 2017-10-30 20:33
@ben-gibson apparently `gradle-intellij-plugin` cannot directly affect the performance of IDE. Please use IDE's issue tracker to report performance issues.

**Comment by halirutan** [comment] 2017-11-01 08:55
@zolotov @ben-gibson To give some insight. I tested it right now on OS X and I could not reproduce my own issue. However, on Linux I'm almost certain that it was connected to having the tool-window open in task execution mode like this

<img width="591" alt="screen shot 2017-11-01 at 09 45 29" src="https://user-images.githubusercontent.com/511683/32266948-c0b64110-bee9-11e7-9e03-484520e0b643.png">

IDEA started up and when I tried to browse the file tree on "Open Project", it had a very noticeable lag. Navigating from one item to another was extremely slow. I see now, that the Gradle task runs disconnected from the main IDEA but back then, I thought some communication between the main IDEA and the sandbox created the slow-down.

I will test this tonight again on my Linux box. In the mean-time, maybe @ben-gibson can provide the operating system he is running on. And maybe you can test if the text mode (the "AB" button in the image) influences the speed.

**Comment by ben-gibson** [comment] 2017-11-01 09:22
I'm having the issue on OSX, until I close the tool-window the whole machine struggles from the CPU load. It only happens when using the task 'runIde' which I guess is because it runs indefinitely while the sandbox is running.

**Comment by halirutan** [comment] 2017-11-01 09:32
@ben-gibson Yes, you are correct. I guess I don't saw the impact since I have a strong machine here. On my OS X, when the tool-window is open in task-execution mode, I constantly see 50% CPU usage

<img width="858" alt="screen shot 2017-11-01 at 10 27 24" src="https://user-images.githubusercontent.com/511683/32268508-99dd420e-beef-11e7-8962-e00d7369a32a.png">

As soon as I switch to text mode or close the tool-window completely, it drops well below 5%. This is the usage of the main IDEA. The sandbox is a different process.

**Comment by zolotov** [comment] 2017-11-01 09:32
The plugin knows nothing about IDEA, tool windows or anything else and I know nothing about supporting Gradle in IDEA. Again, please use IDE's issue tracker to report performance issues.

**Comment by bjansen** [comment] 2018-11-06 21:10
It looks like the problem is caused by the IDE, not by `gradle-intellij-plugin`:

https://youtrack.jetbrains.com/issue/IDEA-199623

**Comment by bjansen** [comment] 2018-12-06 19:18
Fixed in the upcoming IDEA 2018.3.2, I believe you can close this issue.

**Comment by zolotov** [comment] 2018-12-07 12:33
@bjansen thanks for the update!

**Closed by zolotov** 2018-12-07 12:33 UTC
Labels: feedback required, question
