### ISSUE TITLE
pluginVerifier doesn't fail when compatibility issues are found

### ISSUE THREAD

**Issue by rock3r** [JetBrains/gradle-intellij-plugin#573] opened 2020-11-30 11:40 UTC
In my project, I have:

```properties
ideaVersion=2019.2.4

pluginSinceBuild=192.5728.98
pluginUntilBuild=203.*
pluginVerifierIdeVersions=2019.2.4,2019.3.5,2020.1.4,2020.2.4,203.5981.114
```

When running the pluginVerifier, I get told that the plugin is compatible with 2020.1.4, 2020.2.4, and 203.5981.114; but that it's not compatible with 2019.2.4, and 2019.3.5. Yet, the task completes and I get a `BUILD SUCCESSFUL` result.

I'd expect the build to fail if any compatibility issues are found though.

CC @hsz — you know the project I'm talking about :)

**Comment by hsz** [comment] 2020-11-30 12:01
There's a possibility to configure the failure level using property called `failureLevel`. 🙃

I'll mark it as a duplicate of  #557 - docs should be extended a bit.

**Comment by rock3r** [comment] 2020-11-30 12:02
TIL, thanks!

**Closed** 2020-11-30 12:01 UTC
Labels: documentation, duplicate
