### ISSUE TITLE
gradle intellij config set pluginName was error

### ISSUE THREAD

**Issue by SShnoodles** [JetBrains/gradle-intellij-plugin#770] opened 2021-08-20 02:12 UTC
## build.gradle

```
plugins {
    id 'java'
    id "org.jetbrains.intellij" version "1.1.4"
}

intellij {
    pluginName 'XXXX'
    updateSinceUntilBuild false
}
```

## error info

```
> No signature of method: build_4gbeco9hmspmnvwm3ndvyd0bp.intellij() is applicable for argument types: (build_4gbeco9hmspmnvwm3ndvyd0bp$_run_closure3) values: [build_4gbeco9hmspmnvwm3ndvyd0bp$_run_closure3@39bb91c6]
```

> but i just set  `version` was normal

## env

* gradle version: 7.1
* java version: 11

**Comment by hsz** [comment] 2021-08-20 05:18
Duplicate of #694

**Closed by hsz** 2021-08-20 05:18 UTC
