### ISSUE TITLE
Unable to run tests with optional plugin dependencies

### ISSUE THREAD

**Issue by cedricziel** [JetBrains/gradle-intellij-plugin#567] opened 2020-11-14 16:04 UTC
The Plugin in question: https://github.com/cedricziel/idea-php-typo3-plugin/pull/339 

From the build log:

```
        Caused by:
        java.util.concurrent.ExecutionException: com.intellij.testFramework.LoggedErrorProcessor$TestLoggerAssertionError: class com.jetbrains.php.PhpIndexImpl cannot be cast to class com.jetbrains.php.PhpIndex (com.jetbrains.php.PhpIndexImpl is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @3f0299c1; com.jetbrains.php.PhpIndex is in unnamed module of loader 'app')
            at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
            at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
            at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.checkForExceptions(CodeCompletionHandlerBase.java:360)
            ... 21 more

            Caused by:
            com.intellij.testFramework.LoggedErrorProcessor$TestLoggerAssertionError: class com.jetbrains.php.PhpIndexImpl cannot be cast to class com.jetbrains.php.PhpIndex (com.jetbrains.php.PhpIndexImpl is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @3f0299c1; com.jetbrains.php.PhpIndex is in unnamed module of loader 'app')
```

The project builds 3 modules. The `lang-fluid` one has an optional dependency to the PHP plugin.

When building the project, the tests from that module fail, with what it seems, classloader issues.

The problems occurred when upgrading the dependencies from 2020.2 to 2020.3-eap. I have filed an issue over at [JetBrains YouTrack here](https://youtrack.jetbrains.com/issue/IDEA-254896).

In Slack, i got advice to upgrade to the 0.7 Snapshot of the gradle plugin, which resulted in this error:

```
* What went wrong:
com/jetbrains/plugin/structure/intellij/plugin/IdePlugin
> com.jetbrains.plugin.structure.intellij.plugin.IdePlugin
```

I then applied the suggestion from [this issue](https://github.com/JetBrains/gradle-intellij-plugin/issues/562), which leaves me with a new error (exemplary):

<details>
  <summary>Build error</summary>

```
com.cedricziel.idea.fluid.lang.parser.ParserTest > testArrayAccessExpressionCanBeUsedAsViewHelperArgument FAILED
    com.intellij.testFramework.LoggedErrorProcessor$TestLoggerAssertionError: com/jetbrains/php/lang/psi/visitors/PhpRecursiveElementVisitor
        at com.intellij.testFramework.LoggedErrorProcessor.processError(LoggedErrorProcessor.java:39)
        at com.intellij.testFramework.TestLogger.error(TestLogger.java:26)
        at com.intellij.openapi.diagnostic.Logger.error(Logger.java:185)
        at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:412)
        at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1137)
        at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:393)
        at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
        at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:392)
        at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:368)
        at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:172)
        at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:183)
        at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:366)
        at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

        Caused by:
        java.lang.NoClassDefFoundError: com/jetbrains/php/lang/psi/visitors/PhpRecursiveElementVisitor
            at java.base/java.lang.ClassLoader.defineClass1(Native Method)
            at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
            at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151)
            at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:825)
            at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:723)
            at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:646)
            at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:604)
            at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
            at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
            at com.cedricziel.idea.fluid.codeInsight.TemplateLineMarkerProvider.collectNavigationMarkers(TemplateLineMarkerProvider.java:25)
            at com.intellij.codeInsight.daemon.RelatedItemLineMarkerProvider.collectNavigationMarkers(RelatedItemLineMarkerProvider.java:31)
            at com.intellij.codeInsight.daemon.RelatedItemLineMarkerProvider.collectSlowLineMarkers(RelatedItemLineMarkerProvider.java:23)
            at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:182)
            at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:91)
            at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:81)
            at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:78)
            at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
            at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:400)
            ... 16 more

            Caused by:
            java.lang.ClassNotFoundException: com.jetbrains.php.lang.psi.visitors.PhpRecursiveElementVisitor
                at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
                at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
                at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
                ... 34 more

```

</details>

I'm really out of options here, any help appreciated :)

**Comment by hsz** [comment] 2020-11-23 12:29
Reverting to the `0.6.3` version fixed the problem. Marking as a duplicate of #570. Stay tuned. :-)

**Closed by hsz** 2020-11-23 12:29 UTC
