### ISSUE TITLE
Build failed with "Failed to notify progress listener." in IDEA 2018.3

### ISSUE THREAD

**Issue by MichaelShumenko** [JetBrains/gradle-intellij-plugin#340] opened 2018-11-25 21:28 UTC
Please assist. Looks Gradle plugin doesn't work in IDEA 2018.3

**Comment by MichaelShumenko** [comment] 2018-11-26 15:52
@zolotov It's difficult to understand which details will help you. Could you clarify?

We use 0.3.12 version 

![issue](https://user-images.githubusercontent.com/4786289/49025220-d75d9d80-f1a3-11e8-985b-fd9c00d2996c.png)

**Comment by MichaelShumenko** [comment] 2018-11-26 15:56
Oh! IDEA log wil be helpful. Please check

[idea.log](https://github.com/JetBrains/gradle-intellij-plugin/files/2616292/idea.log)

**Comment by zolotov** [comment] 2018-11-26 16:09
>  It's difficult to understand which details will help you.

Basically, anything that can help me to recreate the issue. Plugin version was a good start :) The `intellij` extension configuration might be useful, as well as detailed output (e.g. with `--info`).

Btw, does this happen when you run e.g. `./gradlew buildPlugin` in the terminal?

**Comment by MichaelShumenko** [comment] 2018-11-26 20:35
`./gradlew buildPlugin` - works fine in terminal

```
  intellij {
    type 'IU'
    version '182.3684.40'
    downloadSources false
    updateSinceUntilBuild = false
    sandboxDirectory "$buildDir/idea-sandbox"

    //pluginName 'com.jedide.apex'
    plugins = ['IntelliLang', 'coverage', 'JavaScriptLanguage', 'CSS', 'AngularJS']
    //updateSinceUntilBuild false
  }
```

**Comment by vladsoroka** [comment] 2018-11-27 11:08
@MichaelShumenko could you share the project to reproduce?

**Comment by MichaelShumenko** [comment] 2018-11-28 14:03
@vladsoroka It is difficult to find Root Couse on my side. Probable you may add more logging to gradle plugin and give me this build?

**Comment by adrianchincm** [comment] 2018-11-29 10:23
On Android Studio after upgrading gradle to 5.0, Java Version 11.0.1
Got this error every time I try to sync project
```
Failed to notify build listener.
> org.jetbrains.plugins.gradle.tooling.util.ModuleComponentIdentifierImpl.getModuleIdentifier()Lorg/gradle/api/artifacts/ModuleIdentifier;
```

Hope this will help if it's related to this error

**Comment by zolotov** [comment] 2018-11-29 10:43
@adrianchincm do you use `gradle-intellij-plugin` in your build?

**Comment by Bo98** [comment] 2018-11-29 18:04
Found this via Google. No, I don't think the Android Studio thing is related to this plugin, but rather the internal Gradle tooling plugin. I don't use gradle-intellij-plugin.

Considering Android Studio 3.2.1 uses IntelliJ 2018.1.6, it could be an incompatibility between Gradle 5.0 and that.

https://pastebin.com/nRAZgSjt

I don't have any issue in 2018.3.1 RC2 but then again I'm not working with a complex Android project there.

**Comment by Bo98** [comment] 2018-11-29 18:13
Seems to work on Android Studio 3.3 RC1 (IntelliJ 2018.2.<something>-based).

@adrianchincm

Either way, not an issue with gradle-intellij-plugin.

**Comment by MichaelShumenko** [comment] 2018-12-02 22:51
@vladsoroka @zolotov Hello, guys! Any updates?

**Comment by zolotov** [comment] 2018-12-06 11:41
>  Probable you may add more logging to gradle plugin and give me this build?

Likely it has nothing to do with the plugin, there is kind of nothing to log. I doubt we can say anything more specific without a sample to recreate it

**Comment by thuytrinh** [comment] 2018-12-07 10:50
@adrianchincm I'm running into the exact failure. Only occurred on Android Studio. Running via terminal just works fine.

```
FAILURE: Build failed with an exception.

* What went wrong:
Failed to notify build listener.
> org.jetbrains.plugins.gradle.tooling.util.ModuleComponentIdentifierImpl.getModuleIdentifier()Lorg/gradle/api/artifacts/ModuleIdentifier;
```

**Comment by zolotov** [comment] 2018-12-10 17:19
ok, closing this since there is no way to recreate the issue and that gradle-intellij-plugin likely has nothing to do with this.

**Closed by zolotov** 2018-12-10 17:19 UTC

**Comment by MichaelShumenko** [comment] 2018-12-12 20:42
I think that progress listener is on gradle-intellij plugin side. Isn't it?

**Comment by zolotov** [comment] 2018-12-12 21:50
@MichaelShumenko I cannot recall any progress listeners in the source code of the gradle-intellij-plugin

**Comment by dgarg20** [comment] 2018-12-14 07:18
Hi Guys, 
I cloned the open source kafka repository and used intellij(2018.1 enterprise) to open the project. After that i specified the gradle home in the config dialog(Using gradle 5.0). It startedd with syncing of project and finally ended up with the bellow error

```bash
Cause: org.jetbrains.plugins.gradle.tooling.util.ModuleComponentIdentifierImpl.getModuleIdentifier()Lorg/gradle/api/artifacts/ModuleIdentifier;
```

**Comment by Bo98** [comment] 2018-12-14 09:15
IntelliJ 2018.1 simply does not work with Gradle 5 but 2018.2 or later does.

**Comment by MichaelShumenko** [comment] 2018-12-15 18:35
@zolotov How to idea status bar shows progress while refreshing gradle project? Is it subscribe to some events from daemon gradle process?

**Comment by mikehardy** [comment] 2018-12-22 03:45
I also landed here via Google. 

For future searchers that came here seeing this in Android Studio after upgrading to Gradle 5.0, be aware that the official documentation warns that you may need to upgrade Android Studio to 3.4 (only on Canary and Dev channels as I type this, with 3.3 still at RC3 and not stable) in order to work.

So this issue is apparently about already resolved incompatibilities / issues and you simply need to stay with Gradle 4.10.3 (as I write this) until Android Studio 3.4 is stable enough for you. Cheers

https://docs.gradle.org/5.0/userguide/upgrading_version_4.html - 
```
If you are using Gradle for Android, you need to move to version 3.4 or 
higher of both the Android Gradle Plugin and Android Studio.
```

**Comment by samaitra** [comment] 2019-01-04 02:51
Updating Intellij Idea to 2018.3 worked for me.

**Comment by Technay** [comment] 2019-01-07 05:54
> Hi Guys,
> I cloned the open source kafka repository and used intellij(2018.1 enterprise) to open the project. After that i specified the gradle home in the config dialog(Using gradle 5.0). It started with syncing of project and finally ended up with the bellow error.
> 
> ```shell
> Cause: org.jetbrains.plugins.gradle.tooling.util.ModuleComponentIdentifierImpl.getModuleIdentifier()Lorg/gradle/api/artifacts/ModuleIdentifier;
> ```

Did you find the solution?

**Comment by mikehardy** [comment] 2019-01-07 13:18
@Technay It appears you have read none of the comments. The solution is contained

**Comment by tonyerskine** [comment] 2019-04-15 14:30
Thanks for the help guys. 

I upgraded to Intellij Idea **2019.1** and the problem when away.

**Comment by gcantoni** [comment] 2019-04-25 09:44
Fixed here by updating AS IDE

**Comment by ziemerz** [comment] 2019-11-18 09:12
I am still bumping into this issue from time to time. 

For people who are coming here looking for a solution, killing the Gradle daemon with `./gradlew --stop` and rerunning the build/import fixed it for me

**Comment by futurechallenger** [comment] 2020-08-25 05:36
Intellij => Tool => kotlin => configure kotlin plugin updates fixed this issue for me
