### ISSUE TITLE
Gradle: Could not resolve com.jetbrains.intellij.idea:ideaIC:LATEST-EAP-SNAPSHOT.

### ISSUE THREAD

**Issue by cheikh-sadbouh** [JetBrains/gradle-intellij-plugin#727] opened 2021-07-08 11:23 UTC
can anyone help solving the bellow issue? 

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring root project 'javaplugin'.
> Could not resolve all files for configuration ':detachedConfiguration1'.
   > Could not resolve com.jetbrains.intellij.idea:ideaIC:LATEST-EAP-SNAPSHOT.
     Required by:
         project :
      > Could not resolve com.jetbrains.intellij.idea:ideaIC:LATEST-EAP-SNAPSHOT.
         > Unable to load Maven meta-data from https://cache-redirector.jetbrains.com/www.jetbrains.com/intellij-repository/snapshots/com/jetbrains/intellij/idea/ideaIC/LATEST-EAP-SNAPSHOT/maven-metadata.xml.
            > Could not get resource 'https://cache-redirector.jetbrains.com/www.jetbrains.com/intellij-repository/snapshots/com/jetbrains/intellij/idea/ideaIC/LATEST-EAP-SNAPSHOT/maven-metadata.xml'.
               > Could not GET 'https://www.jetbrains.com/intellij-repository/snapshots/com/jetbrains/intellij/idea/ideaIC/LATEST-EAP-SNAPSHOT/maven-metadata.xml'.
                  > www.jetbrains.com``

**Comment by hsz** [comment] 2021-07-08 21:37
Probably that was a temporary issue – could you please try again?

**Comment by cheikh-sadbouh** [comment] 2021-07-10 20:41
I have tried it once again and resulted with same exception ,you may refer to this [video](https://drive.google.com/file/d/1lMRhlOXAKY-r6vmV3UdYoUrZrt_R8pHB/view?usp=sharing).

**Comment by hsz** [comment] 2021-07-14 11:28
It's not about downloading SDK, but Gradle syntax. `intellij.version` and `patchPluginXml.changeNotes` should use `=` for assignment.
This is the IJ issue that will be fixed in 2021.2

Ref: Migration Guide https://jb.gg/gijp

**Closed by hsz** 2021-07-14 11:28 UTC
Labels: feedback required

**Comment by hsz** [comment] 2021-07-14 11:29
Duplicate of #714
