### ISSUE TITLE
Execute  buildSearchableOptions task get Illegal char error

### ISSUE THREAD

**Issue by Nasller** [JetBrains/gradle-intellij-plugin#1398] opened 2023-06-02 08:14 UTC
**Describe the bug**
execute buildSearchableOptions task get error.
* What went wrong:
Execution failed for task ':buildSearchableOptions'.
> Illegal char <:> at index 25: -Djna.boot.library.path=F:\GradleRepository\caches\modules-2\files-2.1\com.jetbrains.intellij.idea\ideaIU\2023.1\6f24e7c3f8e3f3afd44014d4ade3aba8d78676d6\ideaIU-2023.1/lib/jna/amd64

**To Reproduce**
Task definition
<code>
buildSearchableOptions {
		enabled = env["buildSearchableOptions.enabled"] == "true"
		jvmArgs("-Dintellij.searchableOptions.i18n.enabled=true")
	}
</code>

**Expected behavior**
build success

**Environment:**
 - OS: [Windows 10]
 - Gradle IntelliJ Plugin Version [1.14.0]
 - Gradle Version [8.1]

**Additional context**
Successfully executed in version 1.13.3

**Comment by jhonnen** [comment] 2023-06-02 08:44
`test` is also affected:

```
Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 25: -Djna.boot.library.path=D:\dev\.home\.gradle\caches\modules-2\files-2.1\com.jetbrains.intellij.idea\ideaIC\2022.3\4d343cadac04a0a31d70f6f96facfaa7f949df01\ideaIC-2022.3/lib/jna/amd64
        at org.jetbrains.intellij.Utils.resolveIdeHomeVariable(utils.kt:107)
        at org.jetbrains.intellij.Utils.getIdeaSystemProperties(utils.kt:134)
        at org.jetbrains.intellij.IntelliJPlugin$configureTestTasks$1$3.execute(IntelliJPlugin.kt:1262)
        at org.jetbrains.intellij.IntelliJPlugin$configureTestTasks$1$3.execute(IntelliJPlugin.kt:1255)
```

**Comment by hsz** [comment] 2023-06-02 10:48
I couldn't reproduce it just with the provided details. Could you please prepare a minimal reproducible project?

**Comment by jhonnen** [comment] 2023-06-02 11:09
This works for me:
1. create a new IDE Plugin project via the wizard
2. bump `org.jetbrains.intellij` to `1.14.0` and `intellij.version` to `2022.3`
3. run `gradlew buildSearchableOptions`

**Comment by Nasller** [comment] 2023-06-02 11:22
[CodeGlance Pro](https://github.com/Nasller/CodeGlancePro) try this my project and modify the `libs.versions.toml` file properties `gradleIntelliJPlugin` to `1.14.0`

> I couldn't reproduce it just with the provided details. Could you please prepare a minimal reproducible project?

**Comment by hsz** [comment] 2023-06-02 15:22
I just tested both scenarios on Windows 11 (Parallels) — no error was thrown.

**Comment by hsz** [comment] 2023-06-02 16:15
Fixed with f84543195f72ba6dd3459e9146898d2a177647cc
`1.14.1` will be rolled out soon.

**Comment by Undin** [comment] 2023-06-04 19:39
Sorry, accidentally closed the issue by "fix" comment in https://github.com/JetBrains/educational-plugin repo

**Comment by hsz** [comment] 2023-06-07 08:11
`1.14.1` is now publicly available.

**Closed** 2023-06-07 08:11 UTC
Labels: bug
