### ISSUE TITLE
Cannot download plugin dependency - Scala

### ISSUE THREAD

**Issue by baron1405** [JetBrains/gradle-intellij-plugin#326] opened 2018-10-04 17:48 UTC
I am not sure if this is a problem with the Scala plugin on the plugins repo or with how the gradle-intellij-plugin is referencing it.

I am using version 0.3.11 of gradle-intellij-plugin. The ID of the plugin dependency is org.intellij.scala and the version is 2018.2.11. Downloading directly from the [https://plugins.jetbrains.com/plugin/1347-scala](page on the plugin repo) works. However attempting to build using that plugin as a dependency fails to download the plugin. I have attempted to access [https://cache-redirector.jetbrains.com/plugins.jetbrains.com/maven/com/jetbrains/plugins/org.intellij.scala/2018.2.11/org.intellij.scala-2018.2.11.pom](https://cache-redirector.jetbrains.com/plugins.jetbrains.com/maven/com/jetbrains/plugins/org.intellij.scala/2018.2.11/org.intellij.scala-2018.2.11.pom) directly and get a 404 (same fro jar extension). Other plugins are accessbile using the same maven URL.

**Comment by zolotov** [comment] 2018-10-04 17:54
the problem is on the plugin repo side, I notified the responsible developer

**Comment by baron1405** [comment] 2018-10-04 17:56
Thanks!

**Comment by zolotov** [comment] 2018-10-05 09:43
fixed on the repository side

**Closed by zolotov** 2018-10-05 09:43 UTC

**Comment by baron1405** [comment] 2018-10-05 16:30
Verified on my end as well. Thanks!
